### ISSUE TITLE
Running baseline models on cpu not possible with nvidia docker base image

### ISSUE THREAD

**Issue by PaWeRe** [DIAGNijmegen/picai_baseline#45]
Hi,

I've been trying to do inference with the pre-trained nnDetection baseline models ([picai_nndetection_gc_algorithm](https://github.com/DIAGNijmegen/picai_nndetection_gc_algorithm), [picai_nndetection_gc_algorithm](https://github.com/DIAGNijmegen/picai_nndetection_semi_supervised_gc_algorithm)) on a local prostate MRI dataset. My current approach was to first try to reproduce some of the results mentioned in the pi-cai forum ([here](https://grand-challenge.org/forums/forum/pi-cai-607/topic/baseline-ai-models-for-3d-cspca-detectiondiagnosis-in-bpmri-updates-and-fixes-715/)) on the Public Training and Development Dataset and on my local computer (macos, m1 chip).

It seems the base docker image referenced in the Dockerfile "nvcr.io/nvidia/pytorch:20.12-py3" described in [nndetection_baseline.md](https://github.com/DIAGNijmegen/picai_baseline/blob/main/nndetection_baseline.md) requires an NVIDIA account to be built. Also when using the pre-built version from Docker hub, although the preprocessing of the data works, when trying to run inference on my local machine (no GPU) with 

'docker run -it --rm \
    -v /path/to/workdir:/workdir \
    -v /path/to/images:/input/images \
    joeranbosma/picai_nndetection:latest nndet predict Task2201_picai_baseline RetinaUNetV001_D3V001_3d /workdir \
    --fold -1 --check --resume --input /input/images --output /workdir/predictions/ --results /workdir/results/nnDet' 

a runtime error is generated ('RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx').
Is there an alternative docker base image that one can use for building the dockerfile, compatible with mac silicon architecture + no cuda / nvidia gpu used?

I've tried 'FROM armswdev/pytorch-arm-neoverse:r23.03-torch-1.13.0-openblas' instead, but it created package issues after building, during pre-processing.

Thanks for your help!

Best,
Patrick

**Comment by joeranbosma** [comment]
Hi Patrick,

It's indeed smart to start by recreating some of the results from the linked forum post. 

I'm afraid I cannot help you with the inference issue though, as your issue is with nnDetection framework, which seems to require an NVIDIA GPU. I don't think any base image will solve your issue. You can open an issue on the nnDetection GitHub repository: https://github.com/MIC-DKFZ/nnDetection.

The nnU-Net framework should allow you to use a CPU for inference, so you can try the [semi-supervised nnU-Net baseline](https://github.com/DIAGNijmegen/picai_nnunet_semi_supervised_gc_algorithm). This will be very slow though!

You can also upload your cases to the algorithm on Grand Challenge: [nnDetection (semi-supervised)](https://grand-challenge.org/algorithms/pi-cai-baseline-nndetection-semi-supervised/) or [nnU-Net (semi-supervised)](https://grand-challenge.org/algorithms/pi-cai-baseline-nnu-net-semi-supervised/). Grand Challenge will then process your cases, such that you don't need to set up a local inference pipeline. If you have many cases, you can use the [`gcapi`](https://grand-challenge.org/documentation/grand-challenge-api/) to automate this process.

Hope this helps!

Kind regards,
Joeran

**Comment by PaWeRe** [comment]
Hi Joeran,

thank you for the detailed answer. You're correct, I realized that even inference on CPU will take a very long time with this kind of input data and models. Currently, I am running inference with the supervised pre-trained nndet model on a linux VM on GCP instead. Thanks also for the tip concerning uploading algorithms to the GC platform, I'll look into it (might be difficult tho due to PHI tho).

Best,
Patrick
